name: deploy

on:
  push:
    branches: [master] # master 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install
        run: npm install # 安装依赖

      - name: Build
        run: npm run build # 打包

      # 清理 Edge 浏览器缓存
      - name: Clear Edge Browser Cache
        run: |
          msedge --headless --disable-gpu --remote-debugging-port=9222 --disable-software-rasterizer --disable-dev-shm-usage --no-sandbox --disable-setuid-sandbox --user-data-dir=/tmp --disk-cache-size=1 --disable-background-networking --disable-default-apps --disable-extensions --disable-sync --disable-translate --hide-scrollbars --metrics-recording-only --mute-audio --no-first-run --safebrowsing-disable-auto-update --enable-automation --disable-features=NetworkService,TranslateUI,BlinkGenPropertyTrees --disable-prompt-on-repost --disable-password-generation --disable-password-save --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 about:blank

      # 清理 Chrome 浏览器缓存
      - name: Clear Chrome Browser Cache
        run: |
          google-chrome --headless --disable-gpu --remote-debugging-port=9222 --disable-software-rasterizer --disable-dev-shm-usage --no-sandbox --disable-setuid-sandbox --user-data-dir=/tmp --disk-cache-size=1 --disable-background-networking --disable-default-apps --disable-extensions --disable-sync --disable-translate --hide-scrollbars --metrics-recording-only --mute-audio --no-first-run --safebrowsing-disable-auto-update --enable-automation --disable-features=NetworkService,TranslateUI,BlinkGenPropertyTrees --disable-prompt-on-repost --disable-password-generation --disable-password-save --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 about:blank

      # 清理 Firefox 浏览器缓存
      - name: Clear Firefox Browser Cache
        run: |
          firefox --headless --disable-gpu --remote-debugging-port=9222 --disable-software-rasterizer --disable-dev-shm-usage --no-sandbox --disable-setuid-sandbox --user-data-dir=/tmp --disk-cache-size=1 --disable-background-networking --disable-default-apps --disable-extensions --disable-sync --disable-translate --hide-scrollbars --metrics-recording-only --mute-audio --no-first-run --safebrowsing-disable-auto-update --enable-automation --disable-features=NetworkService,TranslateUI,BlinkGenPropertyTrees --disable-prompt-on-repost --disable-password-generation --disable-password-save --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 about:blank

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./dist # 部署打包后的 dist 目录
          github_token: ${{ secrets.VUE3_DEPLOY }} # secret 名
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: Update Vite2.x + Vue3.x + TypeScript Starter # 部署时的 git 提交信息，自由填写
